<nav class="pcoded-navbar">
    <div class="nav-list">
        <div class="pcoded-inner-navbar main-menu">
            <div class="pcoded-navigation-label">Main</div>
            <ul class="pcoded-item pcoded-left-item">
                <li>
                    <a href="./" class="waves-effect waves-dark lazy">
                        <span class="pcoded-micon">
                            <i class="feather icon-home"></i>
                        </span>
                        <span class="pcoded-mtext">Dashboard</span>
                    </a>
                </li>
                <div class="pcoded-navigation-label">Settings</div>
                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="feather icon-sliders"></i>
                        </span>
                        <span class="pcoded-mtext">Settings</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li >
                            <a href="./site-settings" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Site Settings</span>
                            </a>
                        </li>
                        <li>
                            <a href="./general-settings" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">General Settings</span>
                            </a>
                        </li>
                        <li>
                            <a href="./site-features" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Site Features</span>
                            </a>
                        </li>
                        <li>
                            <a href="./discounts" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Discounts</span>
                            </a>
                        </li>
                        <li>
                            <a href="./loan-settings" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Loan Settings</span>
                            </a>
                        </li>
                        <li>
                            <a href="./ignored-items" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Ignored Items</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <div class="pcoded-navigation-label">Users</div>
                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="feather icon-users"></i>
                        </span>
                        <span class="pcoded-mtext">Users</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li >
                            <a href="./manage-users" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Manage Users</span>
                            </a>
                        </li>
                        <li>
                            <a href="./add-user" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Add User</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <div class="pcoded-navigation-label">Processes</div>
                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                             <!-- <img src="./assets/icons/topup.png" width="100%" height="100%"> -->
                             <i class="feather icon-server"></i>
                        </span>
                        <span class="pcoded-mtext">Transactions</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li>
                            <a href="./all-transactions" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">All Transactions</span>
                            </a>
                        </li>
                        <li>
                            <a href="./manage-networks" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">BTC Transactions</span>
                            </a>
                        </li>
                        <li>
                            <a href="./manage-data-plans" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Manage Data Plans</span>
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                             <img src="./assets/icons/topup.png" width="100%" height="100%">
                        </span>
                        <span class="pcoded-mtext">Airtime - Data</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li>
                            <a href="./airtime-cash" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Airtime to Cash</span>
                            </a>
                        </li>
                        <li>
                            <a href="./manage-networks" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Manage Networks</span>
                            </a>
                        </li>
                        <li>
                            <a href="./manage-data-plans" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Manage Data Plans</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <img src="./assets/icons/pay-bills.png" width="100%" height="100%">
                        </span>
                        <span class="pcoded-mtext">Bills</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li >
                            <a href="./manage-bills" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Manage Bills</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="feather icon-list"></i>
                        </span>
                        <span class="pcoded-mtext">Loans</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <li >
                            <a href="./loan-requests" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Loan Requests</span>
                            </a>
                        </li>
                        <li >
                            <a href="./approved-loans" class="waves-effect waves-dark lazy">
                                <span class="pcoded-mtext">Approved Loans</span>
                            </a>
                        </li>
                    </ul>
                </li>
                <div class="pcoded-navigation-label">Miscellaneous</div>
                <?php /*
                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="feather icon-settings"></i>
                        </span>
                        <span class="pcoded-mtext">Tools</span>
                    </a>
                    <ul class="pcoded-submenu">
                        <!-- <li >
                            <a href="./site-backup" class="btn-diabled waves-effect waves-dark lazy" disabled>
                                <span class="pcoded-mtext">Site Backup</span>
                            </a>
                        </li> -->
                    </ul>
                </li>

                <li class="pcoded-hasmenu">
                    <a href="javascript:" class="waves-effect waves-dark" disabled>
                        <span class="pcoded-micon">
                            <i class="feather icon-layout"></i>
                        </span>
                        <span class="pcoded-mtext">Design</span>
                    </a>
                    <ul class="pcoded-submenu">
                    </ul>
                </li> */?>

                <li style="margin-bottom: 50px">
                    <a href="https://finloan.logad.net/change-log" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="feather icon-star"></i>
                        </span>
                        <span class="pcoded-mtext">Change Log / Support</span>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>
