<!-- footer @s -->
<div class="nk-footer">
    <div class="container-fluid">
        <div class="nk-footer-wrap">
            <div class="nk-footer-copyright"> &copy; <?=date('Y') ?> Ditepay. Designed & Built by <a href="https://popnaija.net" target="_blank">PopNaija Ent.</a>
            </div>
            <div class="nk-footer-links">
                <ul class="nav nav-sm">
                    <li class="nav-item"><a class="nav-link" href="#">Terms</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Privacy</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">Help</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- footer @e -->
</div>
<!-- wrap @e -->
</div>
<!-- main @e -->
</div>

<script type="text/javascript" src="bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>

<script src="bower_components/datatables.net/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
<script src="bower_components/datatables.net-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
<script src="bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js" type="text/javascript"></script>

<script src="admin_assets/js/pjax/pjax.js"></script>
<script type="text/javascript">

    function autoactive(){
        var current = location.pathname;
        $('.pcoded-inner-navbar ul li').removeClass("active");
        $('.pcoded-inner-navbar ul li a').each(function(){
            var $this = $(this);
            new_current = current.split("/")[current.split("/").length-1];
            if (new_current=='') {}
            else{
                // if the current path is like this link, make it active
                if($this.attr('href').indexOf(new_current) !== -1){
                    $this.parent().addClass('pcoded-trigger');
                    if ($("#pcoded").attr("pcoded-device-type")=="mobile" || $("#pcoded").attr("pcoded-device-type")=="phone") {
                        setTimeout($("#mobile-collapse").click(),1000);
                    }
                }
            }
        })
    }
    //PJAX
    var pjax;
    var initButtons = function() {
        var buttons = document.querySelectorAll("a.lazy");
        if (!buttons) {
            return;
        }
    };
    document.addEventListener("pjax:success", function() {
      initButtons();
      autoactive();
      re_init();
    });
    document.addEventListener("DOMContentLoaded", function() {
      pjax = new Pjax({
        elements: ["a.lazy"],
        selectors: ["title",".pcoded-content"],
        cacheBust: true
      });
      initButtons();
      autoactive();
      re_init();
    });

    function re_init(){
        if (!$.fn.DataTable.isDataTable('.data-table')) {
          $(".data-table").DataTable();
        }
        // $('.data-table').DataTable().destroy();
        $(".data-table").DataTable();
    }

    function reload_page(){
        window.location.reload(true);
    }
</script>

<script src="/admin-cp/asset/assets/js/bundle.js?ver=2.4.0"></script>
<script src="/admin-cp/asset/assets/js/scripts.js?ver=2.4.0"></script>
<!-- <script src="/admin-cp/asset/assets/js/dite-settings.js?ver=2.4.0"></script> -->
<script src="/admin-cp/asset/assets/js/inbox.js?ver=2.4.0"></script>
<script src="/admin-cp/asset/assets/js/libs/tagify.js?ver=1.0"></script>
<script src="/admin-cp/asset/assets/js/charts/gd-default.js?ver=2.4.0"></script>
</body>

</html>
