<!DOCTYPE html>
<html lang="zxx" class="js">

<head>
    <!-- <base href="./admin-cp"> -->
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A powerful and conceptual apps base dashboard template that especially build for developers and programmers.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="/admin-cp/asset/images/favicon.png">
    <!-- Page Title  -->
    <title>Ditepay Dashboard</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="/admin-cp/asset/assets/css/dashlite.css?ver=2.4.0">
    <link id="skin-default" rel="stylesheet" href="/admin-cp/asset/assets/css/theme.css?ver=2.4.0">
    <script type="text/javascript" src="/account/bower_components/jquery/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" defer></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
</head>
<script>

var number_format = new Intl.NumberFormat(undefined, {style: 'currency', currency: 'NGN',});
</script>

<body class="nk-body bg-lighter npc-general has-sidebar ">
    <div class="nk-app-root">
              <!-- main @s -->
              <div class="nk-main ">
